version: '3.8'

services:
  # Redis Cache Service / Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: ai-migration-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - ai-migration-network
    restart: unless-stopped

  # Backend API Service / 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: ai-migration-backend
    ports:
      - "8000:8000"
    environment:
      # Redis Configuration
      - REDIS_URL=redis://redis:6379/0
      
      # AI API Keys (从 .env 文件读取)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      
      # Directories
      - UPLOAD_DIR=/app/data/uploads
      - OUTPUT_DIR=/app/data/outputs
      - CACHE_DIR=/app/data/cache
    volumes:
      - ./data:/app/data
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-migration-network
    restart: unless-stopped

  # Frontend Service / 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-migration-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - ai-migration-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  ai-migration-network:
    driver: bridge
